# Generated by Django 5.0.6 on 2026-08-12 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.CharField(help_text='12-digit Aadhar number (digits only).', max_length=12)),
                ('aadhar_document', models.FileField(help_text='Scan/photo of the Aadhar card (PDF, JPG or PNG).', upload_to='users/driver_kyc/aadhar/')),
                ('license_number', models.CharField(max_length=30)),
                ('license_document', models.FileField(help_text='Scan/photo of the driving license.', upload_to='users/driver_kyc/license/')),
                ('license_expiry_date', models.DateField(blank=True, help_text='Date the driving license itself expires.', null=True)),
                ('vehicle_number', models.CharField(help_text='Registration number, e.g. TN09AB1234.', max_length=20)),
                ('vehicle_document', models.FileField(blank=True, help_text='RC book / vehicle registration certificate (optional).', null=True, upload_to='users/driver_kyc/vehicle/')),
                ('renewal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount generated/paid for the last license or vehicle renewal.', max_digits=10, null=True)),
                ('renewal_due_date', models.DateField(blank=True, help_text='Next renewal due date for license/vehicle documents.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver KYC',
                'verbose_name_plural': 'Driver KYC records',
            },
        ),
        migrations.CreateModel(
            name='FarmerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_certificate_number', models.CharField(blank=True, max_length=60)),
                ('iso_certificate_document', models.FileField(help_text='ISO / organic / food-safety certificate (PDF, JPG or PNG).', upload_to='users/farmer_kyc/iso_certificate/')),
                ('iso_issue_date', models.DateField(blank=True, null=True)),
                ('iso_expiry_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer KYC',
                'verbose_name_plural': 'Farmer KYC records',
            },
        ),
    ]
