# Generated by Django 5.0.6 on 2026-08-12 16:43

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverkyc_farmerkyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverkyc',
            name='aadhar_document',
            field=models.FileField(help_text='Scan/photo of the Aadhar card (PDF, JPG or PNG, max 5 MB).', upload_to='users/driver_kyc/aadhar/', validators=[accounts.validators.validate_kyc_document]),
        ),
        migrations.AlterField(
            model_name='driverkyc',
            name='license_document',
            field=models.FileField(help_text='Scan/photo of the driving license (PDF, JPG or PNG, max 5 MB).', upload_to='users/driver_kyc/license/', validators=[accounts.validators.validate_kyc_document]),
        ),
        migrations.AlterField(
            model_name='driverkyc',
            name='vehicle_document',
            field=models.FileField(blank=True, help_text='RC book / vehicle registration certificate (PDF, JPG or PNG, max 5 MB; optional).', null=True, upload_to='users/driver_kyc/vehicle/', validators=[accounts.validators.validate_kyc_document]),
        ),
        migrations.AlterField(
            model_name='farmerkyc',
            name='iso_certificate_document',
            field=models.FileField(help_text='ISO / organic / food-safety certificate (PDF, JPG or PNG, max 5 MB).', upload_to='users/farmer_kyc/iso_certificate/', validators=[accounts.validators.validate_kyc_document]),
        ),
    ]
