# Generated by Django 5.0.6 on 2026-08-13 05:20

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driverkyc_aadhar_document_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.FreshTraceUserManager()),
            ],
        ),
    ]
