# Generated by Django 5.2.17 on 2026-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employee_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='can_report_damage',
            field=models.BooleanField(default=False, help_text='Audit store products and report damaged/spoiled stock for admin review.'),
        ),
    ]
