# Generated by Django 5.2.17 on 2026-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employeepermission_can_report_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('driver', 'Driver'), ('farmer', 'Farmer'), ('employee', 'Employee'), ('support_staff', 'Support Staff')], default='customer', help_text='Determines dashboard access and post-login redirect.', max_length=20),
        ),
    ]
