# Generated by Django 5.2.17 on 2026-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverkyc',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth of the driver (must be at least 18 years old).', null=True),
        ),
    ]
