# Generated by Django 5.2.17 on 2026-08-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_approval_damage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productdamage',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Farmer or employee who filed this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productdamage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdamage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productdamage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Farmer self-reports are auto-approved. Employee reports start Pending and only affect stock once an admin approves them.', max_length=10),
        ),
    ]
