# Generated by hand to match the 0002/0003 migration style in this app.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productdamage_reported_by_productdamage_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_quantity',
            field=models.PositiveIntegerField(
                default=1,
                help_text=(
                    'For farmer-added products: the number of units the price/cost above was quoted '
                    'for (e.g. 22, if you are quoting your price for a lot of 22 pieces). Leave as 1 '
                    'if the price above is already for a single unit.'
                ),
            ),
        ),
    ]
