# Generated by Django 5.2.17 on 2026-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_bulk_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden_by_farmer',
            field=models.BooleanField(default=False, help_text='Farmer removed this from THEIR OWN product list only (dashboard.views.farmer_product_delete). Purely cosmetic on the farmer side — it never touches is_active, so it has zero effect on the admin Inventory page, the customer store, or any existing/future OrderItem rows. Distinct from is_active, which is the flag that actually controls customer-facing visibility.'),
        ),
    ]
