# Generated by Django 5.2.17 on 2026-08-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_rejected_at_product_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Farm/Store GPS Latitude for pickup routing', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Farm/Store GPS Longitude for pickup routing', max_digits=9, null=True),
        ),
    ]
