# Generated by Django 5.2.17 on 2026-09-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_farm_latitude_farm_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='When this batch was harvested from the farm fields.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='received_date',
            field=models.DateField(blank=True, help_text='When this product arrived at our store / inventory warehouse.', null=True),
        ),
    ]
