# Generated by Django 5.2.17 on 2026-08-31 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('interactive_message_sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer_replied', models.BooleanField(db_index=True, default=False)),
                ('customer_replied_at', models.DateTimeField(blank=True, null=True)),
                ('followup_template_sent', models.BooleanField(db_index=True, default=False)),
                ('followup_template_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_followups', to='orders.order')),
            ],
            options={
                'verbose_name': 'WhatsApp Follow-Up',
                'verbose_name_plural': 'WhatsApp Follow-Ups',
                'ordering': ['-interactive_message_sent_at'],
            },
        ),
    ]
