# Generated by Django 5.2.17 on 2026-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappfollowup',
            name='customer_reply_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
