# Generated by Django 5.2.17 on 2026-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_webhook', '0002_whatsappfollowup_customer_reply_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappfollowup',
            name='customer_reply_text',
        ),
        migrations.AddField(
            model_name='whatsappfollowup',
            name='last_reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
