# Generated by Django 5.2.17 on 2026-08-19 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='heading',
            field=models.FloatField(blank=True, help_text='Direction of travel in degrees (0-360)', null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed in metres/second', null=True),
        ),
        migrations.CreateModel(
            name='DeliveryLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_metres', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['order', '-recorded_at'], name='tracking_de_order_i_aa33d6_idx'), models.Index(fields=['driver', '-recorded_at'], name='tracking_de_driver__968ceb_idx')],
            },
        ),
    ]
