# Generated by Django 5.2.17 on 2026-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional image or document attached to ticket inquiry.', null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional image or document attached to reply.', null=True, upload_to='support_attachments/'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
